# Generated by Django 4.2.11 on 2024-04-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
